version: "3.9"
services:
  api:
    build: ./backend
    env_file: ./.env
    ports: ["8000:8000"]
    depends_on: [db, redis]
  web:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports: ["3000:3000"]
    depends_on: [api]
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sdg
      POSTGRES_PASSWORD: sdg
      POSTGRES_DB: sdg17
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  streamlit:
    build: ./streamlit
    ports: ["8501:8501"]
    depends_on: [api]
volumes:
  pgdata:
